# run prod - uvicorn api.server:app --host 0.0.0.0 --port 8000

# Setup backend
# Prerequisites - linux & python
setup:
  curl -LsSf https://astral.sh/uv/install.sh | sh
  $HOME/.local/bin/uv venv
  uv sync

run:
  fastapi dev api/server.py 